# .github/workflows/build-cv.yml
name: Build & Deploy CV

on:
  push:
    paths:
      - 'CV/**'                # rebuild whenever anything under CV/ changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout THIS repo (CV builder)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Install TeX Live & Pandoc
      - name: Install TeX Live & Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-latex-extra pandoc

      # 3) Build your CV: run `make` in the CV/ directory
      - name: Build CV PDF
        working-directory: CV
        run: make

      # 4) Checkout your Pages repo into ./site
      - name: Checkout Pages repo
        uses: actions/checkout@v3
        with:
          repository: ChrisG32123/username.github.io
          token: ${{ secrets.GITHUB_TOKEN }}
          path: site

      # 5) Copy the new PDF into the site’s assets folder
      - name: Copy PDF into site
        run: |
          cp CV/output.pdf site/assets/CV.pdf

      # 6) Commit & push the updated PDF back to the Pages repo
      - name: Commit & Push updated CV
        run: |
          cd site
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/CV.pdf
          git commit -m "📄 Update CV (built at ${{ github.sha }})" || echo "No changes to commit"
          git push origin HEAD:main
