name: Build and Deploy CV

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up LaTeX Environment
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          extra_packages: >-
            fontspec
            geometry
            multicol
            xunicode
            xltxtra
            marginnote
            sectsty
            ulem
            hyperref
            polyglossia

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build CV
        run: |
          cd CV
          make

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: ChrisG32123/ChrisG32123.github.io
          publish_branch: main
          publish_dir: CV
          user_name: GitHub Actions
          user_email: actions@github.com
